### PR TITLE
Increases leniency of instructor lookups in /courses; fixes #52.

### LINKED ISSUE #52: ASPC Course Scheduler "taught by" Name Handling
The "taught by" section of the ASPC course scheduler currently handles:
- first name
- last night
- last name, first name

but does not handle:
-  first name last name (which is how the ASPC course review website handles professor names)

This caused me to believe that the professor (Mark Allen) of a 2D design class that I wanted to take was still on sabbatical and hence missed out on registering for the class as by the time I found out that he wasn't gone, the class filled up.

### PR DESCRIPTION
**Pull request by mattdahl**
Re: #52. The fundamental problem is that the course API returns instructor data as the following XML: `<Name>Clinton, Hillary</Name>`. So our `Instructor` objects just represent the name as a single string, instead of two fields for first and last name. Before, the the user would have to search only by last name (e.g. "Clinton"), or match the *exact* string that we have for the professor (e.g. "Clinton, Hillary"). Now, the user can search like before but "Hillary Clinton" will also return the desired results.

Not 100% sure on the regex here - not my area of specialty. My logic is that `(?!-)` is a lookahead for hyphen characters to explicitly exclude them (to account for last names with hyphens), and then `\W+` captures any non-word characters (e.g. spaces or commas). I then pass that to `re.split()` to split on.

### CODE REVIEW

**Comment by theworldbright** [comment]
Thanks for the fix @mattdahl . I'll put it on staging for a day.

**Comment by theworldbright** [comment]
I loaded the current terms courses onto staging. "Mark Allen", whom Patrick originally tried searching for is returning a match. I've done a couple other tests and it is looking good. If someone else can give me a confirmation, we can push this onto the mainsite. @aspc/digital-media-and-programming-group

**Comment by mattdahl** [comment]
Yeah, it looks okay to me too. *knocks on wood*

**Comment by theworldbright** [comment]
Deployed :+1:

**Pull request merged**
