### PR TITLE
Fix twitter https url bug #98

### PR DESCRIPTION
**Pull request by ZiqiXiong**

### CODE REVIEW

**Comment by KentShikama** [comment]
Can we use something more reliable like https://docs.python.org/2/library/urlparse.html ?

**Comment by ZiqiXiong** [comment]
@KentShikama  urlparse is for parsing clean url into its components, which is different from what we want to do here (extracting url from text). I would say the current implementation is pretty reliable. Can you think of any edge cases that might break this?
screenshot 2016-09-30 00 43 51

**Comment by KentShikama** [comment]
https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#urlize

**Comment by ZiqiXiong** [comment]
@KentShikama Does it extract url from text?

**Comment by KentShikama** [comment]
Quote

"If value is "Check out www.djangoproject.com", the output will be "Check out <a href="http://www.djangoproject.com" rel="nofollow">www.djangoproject.com</a>"."

**Comment by ZiqiXiong** [comment]
Can you embed a templatetag(urlize) inside another templatetag (parse_tweet)?

**Pull request merged**
