### PR TITLE
Create django command that emails users to write course reviews #135

### PR DESCRIPTION
**Pull request by ZiqiXiong**
This PR creates a new command that sends emails requesting for course reviews to all the users that have created a schedule on our Course Search app 90-700 days ago. 

The email template wasn't thoughtfully crafted. Please help me edit them.
screenshot 2016-10-07 21 48 56

Each email is customized, so it should take two to three minutes to send all the emails for schedules generated during one semester. But since we are most likely to call this command through a cron job, this shouldn't affect the functioning of our website.

### CODE REVIEW

**Comment by KentShikama** [comment]
Is there a way to unsubscribe from these emails?

**Comment by ZiqiXiong** [comment]
@KentShikama  Do you have any idea how to unsubscribe users from those kind of emails? Should we create a new UserEmailInfo model? Not sure if that's worth it though.

**Comment by KentShikama** [comment]
I've never done it before but I'm wondering if there isn't already a python package for that

**Comment by ZiqiXiong** [comment]
@KentShikama

**Pull request merged**
